-- Biogenesis: Era 1 — Subsistence items
-- All icons are vanilla placeholders — TODO: replace with custom art

data:extend({
  -- ========== Seeds ==========
  {
    type = "item",
    name = "wheat-seeds",
    icon = "__base__/graphics/icons/coal.png",
    icon_size = 64,
    subgroup = "farm-seeds",
    order = "a[wheat-seeds]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "potato-seeds",
    icon = "__base__/graphics/icons/coal.png",
    icon_size = 64,
    subgroup = "farm-seeds",
    order = "b[potato-seeds]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "flax-seeds",
    icon = "__base__/graphics/icons/coal.png",
    icon_size = 64,
    subgroup = "farm-seeds",
    order = "c[flax-seeds]",
    stack_size = 200,
  },

  -- ========== Raw Crops ==========
  {
    type = "item",
    name = "raw-wheat",
    icon = "__base__/graphics/icons/wood.png",
    icon_size = 64,
    subgroup = "farm-raw-crops",
    order = "a[raw-wheat]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "raw-potatoes",
    icon = "__base__/graphics/icons/wood.png",
    icon_size = 64,
    subgroup = "farm-raw-crops",
    order = "b[raw-potatoes]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "raw-flax",
    icon = "__base__/graphics/icons/wood.png",
    icon_size = 64,
    subgroup = "farm-raw-crops",
    order = "c[raw-flax]",
    stack_size = 100,
  },

  -- ========== Processed Goods ==========
  {
    type = "item",
    name = "flour",
    icon = "__base__/graphics/icons/stone.png",
    icon_size = 64,
    subgroup = "farm-processed",
    order = "a[flour]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "chaff",
    icon = "__base__/graphics/icons/stone.png",
    icon_size = 64,
    subgroup = "farm-processed",
    order = "b[chaff]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "potato-starch",
    icon = "__base__/graphics/icons/stone.png",
    icon_size = 64,
    subgroup = "farm-processed",
    order = "c[potato-starch]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "flax-fiber",
    icon = "__base__/graphics/icons/stone.png",
    icon_size = 64,
    subgroup = "farm-processed",
    order = "d[flax-fiber]",
    stack_size = 100,
  },

  -- ========== Soil & Amendments ==========
  {
    type = "item",
    name = "compost",
    icon = "__base__/graphics/icons/landfill.png",
    icon_size = 64,
    subgroup = "farm-soil",
    order = "a[compost]",
    stack_size = 50,
  },
  {
    type = "item",
    name = "crop-mulch",
    icon = "__base__/graphics/icons/landfill.png",
    icon_size = 64,
    subgroup = "farm-soil",
    order = "b[crop-mulch]",
    stack_size = 100,
  },

  -- ========== Food ==========
  {
    type = "item",
    name = "bread",
    icon = "__base__/graphics/icons/iron-plate.png",
    icon_size = 64,
    subgroup = "farm-food",
    order = "a[bread]",
    stack_size = 100,
  },
  {
    type = "item",
    name = "boiled-potatoes",
    icon = "__base__/graphics/icons/iron-plate.png",
    icon_size = 64,
    subgroup = "farm-food",
    order = "b[boiled-potatoes]",
    stack_size = 100,
  },

  -- ========== Science ==========
  {
    type = "tool",
    name = "botanical-science-pack",
    icon = "__base__/graphics/icons/automation-science-pack.png",
    icon_size = 64,
    subgroup = "farm-science",
    order = "a[botanical-science-pack]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value",
  },

  -- ========== Machine Items (place entities) ==========
  {
    type = "item",
    name = "farm-plot",
    icon = "__base__/graphics/icons/assembling-machine-1.png",
    icon_size = 64,
    subgroup = "farm-machines",
    order = "a[farm-plot]",
    stack_size = 20,
    place_result = "farm-plot",
  },
  {
    type = "item",
    name = "compost-bin",
    icon = "__base__/graphics/icons/wooden-chest.png",
    icon_size = 64,
    subgroup = "farm-machines",
    order = "b[compost-bin]",
    stack_size = 20,
    place_result = "compost-bin",
  },
  {
    type = "item",
    name = "stone-mill",
    icon = "__base__/graphics/icons/stone-furnace.png",
    icon_size = 64,
    subgroup = "farm-machines",
    order = "c[stone-mill]",
    stack_size = 20,
    place_result = "stone-mill",
  },
  {
    type = "item",
    name = "drying-rack",
    icon = "__base__/graphics/icons/wooden-chest.png",
    icon_size = 64,
    subgroup = "farm-machines",
    order = "d[drying-rack]",
    stack_size = 20,
    place_result = "drying-rack",
  },
  {
    type = "item",
    name = "cooking-pot",
    icon = "__base__/graphics/icons/stone-furnace.png",
    icon_size = 64,
    subgroup = "farm-machines",
    order = "e[cooking-pot]",
    stack_size = 20,
    place_result = "cooking-pot",
  },
  {
    type = "item",
    name = "research-bench",
    icon = "__base__/graphics/icons/lab.png",
    icon_size = 64,
    subgroup = "farm-machines",
    order = "f[research-bench]",
    stack_size = 20,
    place_result = "research-bench",
  },
})
