-- Biogenesis: Map Generation (data phase)
--
-- We intentionally do NOT modify tile autoplace here. Vanilla terrain
-- generates normally so the player spawn finder can locate land at origin.
-- control.lua's on_chunk_generated handler then replaces all tiles with
-- deepwater (except a 3×3 grass island at origin) and destroys all
-- vanilla entities. This avoids Factorio 2.0 noise expression issues.
